osx_image: xcode10.2
language: objective-c
if: tag IS blank
before_install:
- gem install cocoapods -v 1.7
- pod repo update
script:
- travis_wait 30 pod lib lint --allow-warnings
notifications:
  slack:
    secure: m4HD0ZZ2XCXSxinUcKlypQvz5SDhCkx365fTO6s+8y73QYoIeHFhZXeSCOgQseo/JENQx39awNSNMHo6jXAdts5LlPhMYVKXR2sYrJERIS2+NO8nQ6IBS893I4bVoAO4PnfjevjMmE5x5aP05puM627SHOzxXy0+e8hVovrikpwplIMbpp1HKXSxGaPRzlbFo21HGQ2+R5KO16sTEjzeEPQXzgQg3uqkauejPIltp6ijLi0WgJZs1RjjFjRIfa83brAaqNG335wO4NokGupx1TKMhu1YRW20BlPHS1yZxEHNEGsms0fyzL3zUju+4UEJcwbXPt4Gxkzb8ZnVOCRyrBQEJeDtrhTfHpSa2e/tSziyZoO8+bxHpq0gA411ZkgdlZ4HQ4EuPEqqZFgkWvQBMsa6z9Z3QURs+Z0rnPtfKTR/wmE7UbcZUGui3l5mpYaT1EGeeu4ZGbbud3UkxXQiryvUNMpXRLKJE5bCboxXI/UtE/Pi5BBrulD5Gds8JSHvC1SpI73zR4W2LzhN63Dodk6hM+0XnP4irbgGh53JcueQctiKJKUrht9qGdMcniUpZdsdFNymJrL2uZg2Ndx3ehcMHvFMLWo4mV4+eyiq2NNVFCcvok/6AEhahX0Sbf2pMayi3OAw81AzAIm3PnlMETpVPhWjb2x63973CObqEQA=
